### ISSUE TITLE
Add scribe transport

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-finagle#12]
Especially as we fix semantic bugs and add features not upstream, we'd be best off getting more users testing this codebase.

@klingerf if you are using scribe, would you be up for testing if we did this?
would any others be up for it?

**Comment by klingerf** [comment]
@adriancole Definitely, I'd be happy to help test.  I'll also thinking about creating a linkerd tracer plugin to support kafka and http as well.
