### ISSUE TITLE
test and publish 2.12 scala, too

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-finagle#21]
Finagle 0.41 starts supporting scala 2.12

To support this here, we'd want to run a matrix build, affecting the scala.version property
On publish, after releasing 2.11, we would replace _2.11 with _2.12 in each artifact id either via a plugin or shell script

**Comment by adriancole** [comment]
cc @openzipkin/devops-tooling @kristofa @eirslett

**Comment by crispywalrus** [comment]
so 2.12 is pretty mainstream at this point. is there any chance of internal movement on this?

**Comment by adriancole** [comment]
first step beyond finagle supporting 2.12 was someone asking to do it :)

**Comment by crispywalrus** [comment]
As i see it there are two things needed here
+ add java8 + 2.12
+ decide to support old versions of java or not

Thing is, finagle now requires java8 as does 2.12. I'm not sure how to proceed as there's a policy question, plus if you wish to keep on supporting older versions some kind of maven voodoo will have to be performed, voodoo that I don't know.

**Comment by eirslett** [comment]
I guess the easiest option is to only support 2.12 going forward, and then point people to older releases if they need 2.11 support. Backports can be made manually on a case-by-base basis, or people can maintain in-house forks if they really need to.

**Comment by crispywalrus** [comment]
Building with 2.12 against 6.42.0 works for me

**Comment by adriancole** [comment]
>
> I guess the easiest option is to only support 2.12 going forward, and then
> point people to older releases if they need 2.11 support. Backports can be
> made manually on a case-by-base basis, or people can maintain in-house
> forks if they really need to.
>
great idea! @klingerf does this work for you?

**Comment by klingerf** [comment]
Thanks for looping me in. My preference would be for this repo to follow the same publishing strategy as finagle itself, which at the moment means publishing both 2.11 and 2.12. Linkerd still depends on finagle 2.11, and I'm concerned about a situation where linkerd upgrades to a new version of finagle, still on 2.11, but there isn't a 2.11 artifact from this repo at the same version of finagle.

That said, we only use these artifacts in the [linkerd-zipkin](https://github.com/linkerd/linkerd-zipkin), and that repo doesn't have a lot of traction yet. I don't want to block forward progress on this issue for a minor dependency. So if it's too much work to publish both, I'd also be OK with switching to 2.12, and we can deal with dependency issues later if they arise.

I created linkerd/linkerd#1128 to track upgrading linkerd to 2.12, but we don't have a timeline for that established yet.

**Comment by adriancole** [comment]
ok so seems we should do a double-release at least for a while. Presuming
the release scripts work off a branch.. (maybe!), we could cut a branch for
2.11 and then on master make a commit to change to 2.12.

We could then do on-demand releases off the 2.11 branch (by cherry-picking
commits off master except the one to switch to 2.12). For example, we could
be lazy and only do 2.11 ever so often.

@abesto wdyt?

**Comment by adriancole** [comment]
also cc @kristofa who I think maybe possibly might be using this :P

**Comment by abesto** [comment]
`publish.sh` currently assumes the only thing valid for release is `master`, namely at https://github.com/openzipkin/zipkin-finagle/blob/master/travis/publish.sh#L117-L119 and https://github.com/openzipkin/zipkin-finagle/blob/master/travis/publish.sh#L129. At first glance it should be possible to pass in an ENV var to the script and use the branch specified there instead of `master`. `travis.yml` can set ENV variables, it can differ by branch, so it's all very tidy. Depending on how much I'm missing, this may be a good intro-level task for learning about how we publish stuff, or it may be a total nightmare. Helpful? ;)

**Comment by klingerf** [comment]
> We could then do on-demand releases off the 2.11 branch (by cherry-picking
commits off master except the one to switch to 2.12). For example, we could
be lazy and only do 2.11 ever so often.

This approach works for me. Thanks @adriancole!

**Comment by adriancole** [comment]
I'm going to do a version bump, then a release to both versions

**Comment by adriancole** [comment]
howdy folks. if you have opinions on scala 2.13, please help out chris by commenting on #78
