### ISSUE TITLE
Passing flags as arguments

### ISSUE THREAD

**Issue by melgenek** [openzipkin/zipkin-finagle#24]
Currently flags can be passed only as system properties that is not very convenient when using docker entrypoint and variable arguments via command parameters.

It seems that there are some reasons for this:
* `HttpZipkinTracerFlags` is located in `zipkin.finagle.http` package but accoding to `GlobalFlag` javadoc it should be in the same package as the global flag. So either the flag should be renamed or the class should be moved to `zipkin.finagle.http`
* It seems that global flags should be top level classes. So `host` should be moved outside HttpZipkinTracerFlags
* there is also `JavaGlobalFlag` flag that has example for creating flag with java.

**Comment by adriancole** [comment]
If flags aren't working from the CLI, we should fix that. Hopefully without
resorting to package renaming etc as that's not very idiomatic in java.
Let's see what we have to do to make this work.

**Comment by adriancole** [comment]
ps sorry dropped this. I think more important than java idiomatic is that some flag will need to be duplicated in multiple jars. The duplication problem may not be as big a problem as lack of CLI params, so maybe that's ok.

**Comment by adriancole** [comment]
going out as 0.3.5
