### ISSUE TITLE
Bump to version 1.0

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-finagle#33]
We haven't broken api in a while, probably a good time to formalize that with a 1.0 version.

what do you think @klingerf and anyone else?

**Comment by klingerf** [comment]
Works great for me, and linkerd [switched to scala 2.12](https://github.com/linkerd/linkerd/pull/1257) awhile back, so we can consume the 2.12 artifacts from here forward (not sure if that impacts the 1.0 decision or not, but figured I'd mention it).

**Comment by adriancole** [comment]
1.0.0 on the way
