### ISSUE TITLE
Keep pace with finagle's new cadence

### ISSUE THREAD

**Issue by ghost** [openzipkin/zipkin-finagle#38]
Twitters finagle team has started releasing new versions of finagle on a monthly basis. These releases are 'versioned' via a year.month.patch scheme to point out that finagle doesn't follow semantic versioning. This project should follow the pace of the twitter team and keep versions up to date.

**Comment by adriancole** [comment]
Sure.. feel free to raise a pull request or nag us on gitter if a release
is missed.

**Comment by adriancole** [comment]
ps release 1.1.1 is going out now with latest versions. thanks for the ping

**Comment by adriancole** [comment]
ps I put in a calendar notification as seems this is every 17th. 1.1.2 going out now.

ps @schrepfler @klingperf @mosesn are any of you in a position to help remember do releases if you had karma to do so? (bump version in maven file and push tag) I might be on holiday one 17th of the month!

**Comment by adriancole** [comment]
I meant @klingerf (somehow I always read "kling perf" like klingon performance)

**Comment by schrepfler** [comment]
Finished in akka land for the moment so less engaged with Finagle but if it hit's my radar will do!

**Comment by mosesn** [comment]
@adriancole fwiw, the 17th just happened because we ran into a bunch of issues trying to upgrade our build tool.  We generally try to shoot for earlier in the month.  I'll try to remember to ping you–what are good ways to reach out?

**Comment by adriancole** [comment]
thx for the info, moses. gitter or even pinging this issue work
https://gitter.im/openzipkin/zipkin

**Comment by mosesn** [comment]
@adriancole https://finagle.github.io/blog/2017/12/12/release-notes/

**Comment by adriancole** [comment]
thx for the ping. up to date here

**Comment by mosesn** [comment]
@adriancole http://finagle.github.io/blog/2018/01/17/release-notes/

**Comment by adriancole** [comment]
thanks v1.2.1 on the way now

**Comment by mosesn** [comment]
@adriancole http://finagle.github.io/blog/2018/03/06/release-notes/

Sorry, I missed February!

**Comment by adriancole** [comment]
1.2.3 on the way. thanks!

**Comment by crispywalrus** [comment]
@adriancole https://finagle.github.io/blog/2018/04/11/release-notes/

**Comment by adriancole** [comment]
thanks, chris.

PS would you be up to having access to cut this?
right now, you can see the change log. I edit the pom.xml file. then I
push a tag like release-1.2.4 which sets things in motion to publish
the version. I choose a patch version number unless we actually
changed the code.

Would you like access to do the same?

**Comment by chris-vale-ck** [comment]
@adriancole I'd be fine in doing so in my Credit Karma professional capacity. Bumping versions once a month isn't a big deal to me. I have to chase the twitter ecosystem anyway.

**Comment by adriancole** [comment]
welcome! and thank you (and by extension Credit Karma).

you now have Karma. There's a RELEASE.md which is the longer version of what I mentioned. if you run into any problems with the next release, Chris, ping me via any mechanism you prefer. I'm usually on gitter.

**Comment by schrepfler** [comment]
@adriancole https://finagle.github.io/blog/2018/08/07/release-notes/

**Comment by chris-vale-ck** [comment]
@schrepfler are you having an issue with the current release. I did have to make some minor code changes but things seems to be testing correctly.

**Comment by schrepfler** [comment]
I haven't, I just picked up on the release and thought to share on the tread (and noticed the mention of tracing in the release notes so attached them as well).

**Comment by crispywalrus** [comment]
I'm pretty sure this is resolved
