### ISSUE TITLE
Publish of 1.2.3 failed

### ISSUE THREAD

**Issue by chris-vale-ck** [openzipkin/zipkin-finagle#42]
During the publish for 1.2.3 the actual publish then roll to next development version failed. The versions rolled but no artifacts where actually delivered.

**Comment by adriancole** [comment]
I will check for build flake

**Comment by adriancole** [comment]
weird.. license plugin is acting up again.

**Comment by adriancole** [comment]
trying again

**Comment by adriancole** [comment]
some CI servers report incorrect git dates.. that's happening now, so
I'll disable the license plugin
