### ISSUE TITLE
Redo in java?

### ISSUE THREAD

**Issue by adriancole** [openzipkin/zipkin-finagle#6]
When writing the http tracer, I noticed that there's a lot of ceremony and cruft involved in using the scala language, as well a future requirement to cross-compile. It seems we can avoid at least some of this by just writing the code and tests in java. Finagle's java support is pretty good right now, and it would help conserve time for other tasks in zipkin to not have the burden of things like this.

Since in many cases, users don't interact with this code at all (ex via service loader), the actual user-facing impact is minimal.

If we did this, we could choose to either of the two options, or anything you can think up.

### scala-agnostic jar
make a scala-version-free binary with "provided" dependencies on scala libraries like finagle or kafka 2.11. ex. zipkin-finagle-http.jar as opposed to zipkin-finagle-http_2.11.jar. Users would need to explicitly declare dependencies on scala things, which might be inconvenient.

### scala dependencies jar
build like we are doing today (but more simply as we don't have to compile scala), and publish a _2.11 artifact. When finagle does 2.12 we setup another release job that only changes the artifact names and the dependencies (ex there's literally no code change since it would be java level 7 on our side).

Thoughts?

### details

stuff like making the tracer usable from Java and ServiceLoader.
```scala
  /**
   * Util method since named parameters can't be called from Java
    *
    * @param statsReceiver Where to log information about tracing success/failures
   */
  def mk(statsReceiver: StatsReceiver): Tracer =
    mk(host = hostFlag(), statsReceiver = statsReceiver, sampleRate = sampleRateFlag())
}

class HttpZipkinTracer(
  underlying: HttpRawZipkinTracer,
  sampleRate: Float
) extends SamplingTracer(underlying, sampleRate) {
  /** Default constructor for the service loader */
  def this() = this(
    new HttpRawZipkinTracer(
      host = hostFlag(),
      statsReceiver = DefaultStatsReceiver.scope("zipkin.http")
    ), sampleRateFlag())
}
```

Moreover, there's been concern raised about a future where we'll need to cross-compile
* finagle doesn't do 2.12, yet twitter/finagle#505
* when this becomes relevant we need to update release.sh to release twice, sync once. like https://github.com/Stratio/scala-cross-build-maven-plugin

Next, getting javadoc attachments requires hacks like this..
```java
/**
 * This file is here to allow maven central deploys and avoid the complexity of trying to convert
 * scala to javadoc.
 *
 * See https://issues.sonatype.org/browse/OSSRH-2932
 */
public class InternalJavaDocDummy {
}
```

Finally, the test setup is atrocious, since junit rules are not well integrated into the scala language.

```scala
object HttpRawZipkinTracerTest {
  // Singleton as the test needs to read the actual port in use
  val zipkinRule = new ZipkinRule()

  // Scala cannot generate fields with public visibility, so use a def instead.
  @ClassRule def zipkinDef = zipkinRule
}

class HttpRawZipkinTracerTest extends JUnitSuite {

  import HttpRawZipkinTracerTest.zipkinRule
```

**Comment by adriancole** [comment]
cc @eirslett @sveinnfannar @kristofa I volunteer to do the conversion if y'all are ok with this. I spent way too much time trying to get things to work yesterday, and can help much more effectively if we didn't have to use scala to do this.

**Comment by kristofa** [comment]
I'm fine with converting this to Java only.

**Comment by eirslett** [comment]
Sounds like a good idea to me!

**Comment by sveinnfannar** [comment]
Yes sounds good 👍

**Comment by adriancole** [comment]
update on this.. I've ported the kafka side over, and noticed some code duplication between that and http (especially tests that we need to run). Also, global flags are a pain (though I have gotten them to work in java) See https://github.com/twitter/finagle/issues/536.

I'll probably have a pull request ready in a day or two.

**Comment by adriancole** [comment]
https://github.com/openzipkin/zipkin-finagle/pull/8 uses style largely borrowed from Brave.

In a later pull request, we could consider removing even the base dependency (ex porting DeadlineSpanMap etc to use normal zipkin structs which include Span.timestamp etc)
