### ISSUE TITLE
DefaultTracer resolves to NullTracer when HttpZipkinTracer is on the classpath

### ISSUE THREAD

**Issue by notxcain** [openzipkin/zipkin-finagle#96]
## Describe the Bug
Scala 2.13.5
zipkin-finagle-http_2.13 2.2.4

`DefaultTracer` resolves to `NullTracer` when `HttpZipkinTracer` is on the classpath.

## Steps to Reproduce
I didn't manage to write a failing test because the project failed to build. 
So here's the simplest reproducer.  https://github.com/notxcain/zipkin-http-repro
Just run `sbt run`.

## Expected Behaviour
`DefaultTracer` resolves to `HttpZipkinTracer`

**Comment by jcchavezs** [comment]
Any chance you can review this @crispywalrus?
