### ISSUE TITLE
2.2.5 is not published to Maven Central

### ISSUE THREAD

**Issue by notxcain** [openzipkin/zipkin-finagle#98]
The 2.2.5 artifact is missing from Maven Central https://search.maven.org/search?q=a:zipkin-finagle-http_2.13

**Comment by notxcain** [comment]
Hey @crispywalrus! Could you please take a look at that?

**Comment by crispywalrus** [comment]
The build failed with a authentication error and I don't have access to any openzipkin secrets and such. Not sure who's looking in on this now that adrian is gone. @kristofa could you look a that secrets config please?

**Comment by crispywalrus** [comment]
Resolving this issue. Permissions on the build have been fixed, the publish rerun and I've verified that 2.2.5 has been published from commit 77ca5210ec6c4f3831ebdfb2dc7c26c3fb87f122

**Comment by notxcain** [comment]
@crispywalrus thank you!
