### ISSUE TITLE
META-INF/services is missing in published 2.2.5 artifacts 

### ISSUE THREAD

**Issue by notxcain** [openzipkin/zipkin-finagle#99]
## Describe the Bug

`META-INF/services` directory defined for each subproject in #97 is missing in published 2.2.5 artifacts.

## Steps to Reproduce
Download JAR for `io.zipkin.finagle2:zipkin-finagle-http:2.2.5`. Inspect the contents of `META-INF`.

## Expected Behaviour
`META-INF/services` is present.

This is might be due to incorrect resource configuration in [pom.xml](https://github.com/openzipkin/zipkin-finagle/blob/master/pom.xml#L497). Sorry for that. I don't have any experience with Maven. It worked when I published locally on my machine though.

I'm gonna take a closer look later this week.

**Comment by jcchavezs** [comment]
Ping @crispywalrus

**Comment by anuraaga** [comment]
Seems to be a typo missing `src/` at https://github.com/openzipkin/zipkin-finagle/blob/master/pom.xml#L498

Not sure what `filtering` does but probably good just to copy pasta from https://github.com/openzipkin/brave/blob/master/pom.xml#L598

**Comment by notxcain** [comment]
@crispywalrus Could you please publish artifacts with these changes?
